services:
  - type: web
    name: recipesstore
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn RecipesStore.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: RecipesStore.settings